//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers
    {
        public AspNetUsers()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaims>();
            this.AspNetUserDetails = new HashSet<AspNetUserDetails>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogins>();
            this.Candidates = new HashSet<Candidates>();
            this.Jobs = new HashSet<Jobs>();
            this.AspNetRoles = new HashSet<AspNetRoles>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public string FaxNumber { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string Companyname { get; set; }
        public string Address { get; set; }
        public string ZIP { get; set; }
        public string City { get; set; }
        public Nullable<int> Country { get; set; }
        public string Website { get; set; }
        public string ThumbURL { get; set; }
        public byte[] ThumbImg { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string GooglePlus { get; set; }
        public string Dribble { get; set; }
        public string Pinterest { get; set; }
        public string LinkedIn { get; set; }
        public Nullable<bool> Favorited { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<int> CreditBalance { get; set; }
        public string ThumbSmallSRC { get; set; }
    
        public virtual ICollection<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserDetails> AspNetUserDetails { get; set; }
        public virtual ICollection<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual ICollection<Candidates> Candidates { get; set; }
        public virtual ICollection<Jobs> Jobs { get; set; }
        public virtual ICollection<AspNetRoles> AspNetRoles { get; set; }
    }
}
