//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateSkills
    {
        public int Id_Skill { get; set; }
        public Nullable<int> Id_CV { get; set; }
        public string Title { get; set; }
        public Nullable<int> Level { get; set; }
        public string Description { get; set; }
    
        public virtual Candidates Candidates { get; set; }
    }
}
