//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobs
    {
        public Jobs()
        {
            this.CandidatesApplications = new HashSet<CandidatesApplications>();
            this.JobApplications = new HashSet<JobApplications>();
            this.JobEducation = new HashSet<JobEducation>();
            this.JobExperience = new HashSet<JobExperience>();
            this.JobRequirements = new HashSet<JobRequirements>();
            this.JobSkills = new HashSet<JobSkills>();
        }
    
        public int IdJob { get; set; }
        public Nullable<int> IdWho { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public string VideoSRC { get; set; }
        public string ImageSRC { get; set; }
        public string MarkerImagePath { get; set; }
        public string Titlu { get; set; }
        public string WhereWhat { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string Solicitare { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Orar { get; set; }
        public string Localitate { get; set; }
        public string Address { get; set; }
        public Nullable<double> Latitudine { get; set; }
        public Nullable<double> Longitudine { get; set; }
        public string ZIP { get; set; }
        public string Region { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<double> MinSal { get; set; }
        public Nullable<double> MaxSal { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> WorkPermit { get; set; }
        public Nullable<int> WorkType { get; set; }
        public Nullable<int> WorkIndustry { get; set; }
        public string Experience { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<CandidatesApplications> CandidatesApplications { get; set; }
        public virtual ICollection<JobApplications> JobApplications { get; set; }
        public virtual ICollection<JobEducation> JobEducation { get; set; }
        public virtual ICollection<JobExperience> JobExperience { get; set; }
        public virtual ICollection<JobRequirements> JobRequirements { get; set; }
        public virtual WorkPermit WorkPermit1 { get; set; }
        public virtual WorkType WorkType1 { get; set; }
        public virtual WorkIndustry WorkIndustry1 { get; set; }
        public virtual ICollection<JobSkills> JobSkills { get; set; }
    }
}
