//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSkills
    {
        public int IdSkill { get; set; }
        public Nullable<int> Id_Job { get; set; }
        public string Title { get; set; }
        public Nullable<int> Level { get; set; }
        public string Description { get; set; }
    
        public virtual Jobs Jobs { get; set; }
    }
}
