//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobShopEntities : DbContext
    {
        public JobShopEntities()
            : base("name=JobShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserDetails> AspNetUserDetails { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CandidateEducation> CandidateEducation { get; set; }
        public virtual DbSet<CandidateExperience> CandidateExperience { get; set; }
        public virtual DbSet<CandidateReq> CandidateReq { get; set; }
        public virtual DbSet<Candidates> Candidates { get; set; }
        public virtual DbSet<CandidatesApplications> CandidatesApplications { get; set; }
        public virtual DbSet<CandidateSkills> CandidateSkills { get; set; }
        public virtual DbSet<CandidatesLanguages> CandidatesLanguages { get; set; }
        public virtual DbSet<CandidateViews> CandidateViews { get; set; }
        public virtual DbSet<CVee> CVee { get; set; }
        public virtual DbSet<JobApplications> JobApplications { get; set; }
        public virtual DbSet<JobEducation> JobEducation { get; set; }
        public virtual DbSet<JobExperience> JobExperience { get; set; }
        public virtual DbSet<JobRequirements> JobRequirements { get; set; }
        public virtual DbSet<Jobs> Jobs { get; set; }
        public virtual DbSet<JobSkills> JobSkills { get; set; }
        public virtual DbSet<JobsLanguages> JobsLanguages { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
        public virtual DbSet<WorkContractType> WorkContractType { get; set; }
        public virtual DbSet<WorkExperience> WorkExperience { get; set; }
        public virtual DbSet<WorkIndustry> WorkIndustry { get; set; }
        public virtual DbSet<WorkPermit> WorkPermit { get; set; }
        public virtual DbSet<WorkType> WorkType { get; set; }
    }
}
