//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkIndustry
    {
        public WorkIndustry()
        {
            this.Jobs = new HashSet<Jobs>();
        }
    
        public int IdIndustry { get; set; }
        public string Industry { get; set; }
    
        public virtual ICollection<Jobs> Jobs { get; set; }
    }
}
